


<div id="header">
	<ul class="nav">
		<li><a href="">Inicio</a></li>
		<li><a href="">Roles</a>
			<ul>
				<li><A HREF=""> Webmaster </A></li>
				<!--Ejemplo: <A HREF="otra_pagina.html"> Este es un link </A> !-->
				<li><A HREF=""> Moderador </A></li>
				<li><A HREF=""> Diseñador </A></li>
				<li><A HREF=""> Editor de texto </A></li>
				<ul>
					<li><a href="">Submenu1</a></li>
					<li><a href="">Submenu2</a></li>
				</ul>
		</li>
	</ul>
	</li>
	<li><a href="">Usuarios</a>
		<ul>
			<li><A HREF="/admin/ver-usuarios"> Ver usuarios </A></li>
			<li><a href="/admin/eliminar-usuario">Eliminar un usario</a></li>
		</ul>
	</li>
	<li><a href="">Otros</a>
		<ul>
			<li><A HREF="Link_reacciones">Reacciones</A></li>
		</ul>
	</li>
	<li><A HREF="/admin/contacto">Contacto</a></li>
	</ul>
</div>

<main class="container margin-auto">
	<span class="margin-auto__content">
		¡¡Bienvenidoo a la página del admin!!
	</span>
</main>
