<div id="header">
	<ul class="nav">
		<li><a href="">Inicio</a></li>
		<li><a href="/admin/roles">Roles</a></li>
		<li><a href="/admin/usuarios">Usuarios</a></li>
		<li><a href="/admin/archivos">Archivos</A></li>
		<li><A HREF="/admin/contacto">Contacto</a></li>
	</ul>
</div>
<br><br>

<main class="container">
	<div class="margin-auto__content">
	<h4 class="text">¡¡Bienvenidoo a la página del admin!!</h4>
	</div>
</main>