<main class="container">
	<h1 class="title">Cambiar contraseña</h1>

	<p>Nos comunicaremos con usted, por favor llene el siguiente formulario:</p>
	<div class="login">
		<img class="pollito" src="/think.gif" alt="">
		<form enctype="application/x-www-form-urlencoded" class="ch__login" method="post">
        <div>
            <label for="input-contraseña-antigua">Ingrese su antigua contraseña: </label>
				<input required type="password" id="contraseña-anterior" name="old_pass" placeholder="password"><br>
			</div>
            <div>
            <label for="input-contraseña-nueva">Ingrese la nueva contraseña: </label>
				<input required type="password" id="nueva-contraseña" name="new_pass" placeholder="password"><br>
			</div>
			<div>
				<button type="submit" class="btn_ch">Cambiar contraseña</button>
			</div>
		</form>
	</div>
</main>
