<main class="container">
	<h1 class="title">Cambiar contraseña</h1>
	<p>Oh no, usted ha olvidado su contraseña :(</p>
	<p>Nos comunicaremos con usted, por favor llene el siguiente formulario:</p>
	<div class="login">
		<img class="pollito" src="/public/think.gif" alt="">
		<form enctype="application/x-www-form-urlencoded" class="ch__login" method="post">
			<div>
				<label for="input-correo">Ingrese su correo electrónico: </label>
				<input required class="inpt" type="text" id="input-correo" name="email" placeholder="email@adress.com"><br>
			</div>
			<div>
				<button type="submit" class="btn_ch">Recuperar</button>
			</div>
		</form>
	</div>
</main>