<main class="container">
	<h1>Crear una publicación</h1>

	<form enctype="multipart/form-data" method="post">
		<label>Titulo: </label>
		<input type="text" name="title">
		<label>Imagen: </label>
		<input type="file" name="image">
		<div class="input-group" style="margin-bottom: 1em">
			<label>Cuerpo: (Mínimo 20 caracteres)</label>
			<textarea name="body" rows="10" style="resize: vertical;"></textarea>
		</div>
		<div>
			<input type="submit" name="type" value="Publicar">
			<input type="submit" name="type" value="Guardar">
			<a role="button" href="..">
				<i class="mu mu-cancel"></i>
				Cancelar
			</a>
		</div>
	</form>
</main>
