<main class="container">
    <h1>Eliminar cuenta</h1>
    <form method="post" enctype="application/x-www-form-urlencoded">
        <input type="hidden" name="id" value="<?= htmlspecialchars($_GET['id']) ?>">
        <p>Una vez elimines este usuario, no podra volver a iniciar sesion</p>
        <button type="submit">Eliminar usuario</button>
        <a href="/admin/usuarios" role="button">Regresar</a>
    </form>
</main>
