<div class="container">
    <div class="titulo">
        <h1>Eliminar roles de usuario</h1>

        <h2>Selecciona el rol que quieres eliminar</h2><br>
    </div>
    <form action="/admin" manager="form" class="selector" method="POST" enctype="application/x-www-form-urlencode">
        <select class="cuadro" name="id" id="rol">
            <option value="" disabled selected>--Selecciona un rol</option>
            <?php foreach($this->roles as $rol): ?>             <!-- por cada de los roles se guarda la informacion en cada rol -->
                <option value="<?= $rol['id'] ?>"><?= $rol['name'] ?></option> <!--  -->
            <?php endforeach ?>
        </select>
        <button>
            Enviar
        </button>
    </form>

</div>