<main class="container">
    <h1>Eliminar archivo</h1>
    <form method="post" enctype="application/x-www-form-urlencoded">
        <input type="hidden" name="id" value="<?= htmlspecialchars($_GET['id']) ?>">
        <p>¿Estas seguro de que deseas eliminar el archivo?</p>
        <button type="submit">Eliminar archivo</button>
        <a href="/admin/archivos" role="button">Regresar</a>
    </form>
</main>
