<main class="container">
<h1>Perfil de usuario<i class="mu mu-user"></i></h1>	
<hr>
<div class="login">
	<header class="login__header">
	<h1>Editar mi perfil <i class="mu mu-edit"></i></h1>
	</header>
		<form method="post" enctype="multipart/form-data" class="edit__form">
			<label for="name">Nombre: </label>
		<div class="edit">
			<input type="text" name="name" value="<?= htmlspecialchars($user->username) ?>">
		</div>


		<label for="Cambiar-Foto">Foto actual:</label><br>
		<?php if (!empty($image)) : ?>
			<div class="avatar">
				<?php if (!empty($image)) : ?>
					<img src="<?= $image->path ?>" class="contains" loading="lazy" alt="Imagen de perfil">
				<?php else : ?>
					<img src="/user.png" class="contains" loading="lazy" alt="Imagen de perfil">
				<?php endif ?>
			</div>
			<?php endif ?>
			<label for="Cambiar-Foto">Cambiar foto:</label>
			<input type="file" name="avatar">
			<button type="submit" class="btn_act">Actualizar información</button>
			<a href="/perfil/editar/cambiar-contraseña" role="button" class="back">Cambiar mi contraseña</a>
			<a href="/perfil" role="button" class="back">Regresar</a>
		</form>
	</div>
</main>
