<main class="container">
    <div class="titulo">
        <h1>Editar roles de usuario</h1>

        <h2>Selecciona el rol que quieres cambiar</h2><br>
    </div>
    <form class="selector" method="post" enctype="application/x-www-form-urlencode">
        <select class="cuadro" name="id" id="rol">
            <option disabled selected>Selecciona un rol</option>
            <?php foreach($roles as $rol): ?>
            <option value="<?= $rol['id'] ?>">
                <?= $rol['name'] ?>
            </option>
            <?php endforeach ?>
        </select>
        <input class="cuadro" type="text" placeholder="Cambiar nombre" name="nombre">
        <button>
            Enviar
        </button>
    </form>
</main>
