<main class="container">
	<h1>Actualizar mi perfil
		<hr>
	</h1>
	<form method="post" enctype="multipart/form-data">
		<label for="name">Nombre: </label>
		<div class="edit">
			<input type="text" name="name" value="<?= htmlspecialchars($user->username) ?>">
		</div>

		<?php if (!empty($image)): ?>
		<div class="avatar">
			<label for="avatar">Imagen anterior</label>
			<img src="<?= $image->url() ?>" loading="lazy" alt="Imagen de perfil" class="pfp">
		</div>
		<?php endif ?>
		<label for="Cambiar-Foto">Cambiar foto</label>
		<input type="file" name="avatar">
		<button type="submit">Actualizar informacion</button>
	</form>
</main>
</main>
