<main class="container">
	<h1>Cambiar info del usuario</h1>



	<label for="cambiar-correo">Correo</label>
	<div class="edit">
		<input type="text" id="input-correo" name="email" value="<?= htmlspecialchars($user->email) ?>" disabled>
	</div>



	<form method="post" action="/admin/usuario/editar/nombre" enctype="multipart/form-data">
		<label for="name">Editar nombre</label>
		<div class="edit">
			<input type="text" id="input-nombre" name="name" value="<?= htmlspecialchars($user->username) ?>">
		</div>

		<select class="cuadro" name="rol" id="rol">
			<option disabled selected>Selecciona un rol</option>
			<?php foreach ($roles as $rol) : ?>
				<option value="<?= $rol['id'] ?>">
					<?= htmlspecialchars($rol['name']) ?>
				</option>
			<?php endforeach ?>
		</select>
		<input type="hidden" value="<?= htmlspecialchars($user->id)?>" name="id">
		<button type="submit">Actualizar informacion</button>
	</form>


	<form method="post" action="" enctype="multipart/form-data">
		<label for="Cambiar-Foto">Foto actual</label><br>
		<?php if (!empty($image)) : ?>
			<div class="avatar">
				<?php if (!empty($image)) : ?>
					<img src="<?= $image->url() ?>" class="contains" loading="lazy" alt="Imagen de perfil">
				<?php else : ?>
					<img src="/public/user.png" class="contains" loading="lazy" alt="Imagen de perfil">
				<?php endif ?>
			</div>
		<?php endif ?>
		<label for="Cambiar-Foto">Cambiar foto</label>
		<input type="file" name="avatar">
		<button type="submit">Actualizar informacion</button>
	</form>
	<a href="/admin/usuarios" role="button">Regresar</a>

</main>