<main class="container">
    <h1>Archivos<hr></h1>
    <table>
        <thead>
            <th>Id</th>
            <th>Nombre del archivo</th>
            <th>Tipo</th>
            <th>Tamaño</th>
        </thead>
        <tbody>
            <?php foreach($files as $file): ?>
            <tr>
                <td>
                    <?= $file->id ?>
                </td>
                <td>
                    <a href="<?= $file->url() ?>">
                        <?= strip_tags($file->filename) ?>
                    </a>
                </td>
                <td>
                    <?= strip_tags($file->mime) ?>
                </td>
                <td>
                    <?= $file->size ?> bytes
                </td>
            </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</main>
