<?php

use Modules\Kernel\View;

?>
<?= new View('navbar.phtml') ?>
<main class="container">
	<h1>Iniciar sesión</h1>
	<form enctype="application/x-www-form-urlencoded" method="post">
		<label>Ingresa tu correo: </label>
		<input required type="email" name="email" size="30">
		<label>Ingresa tu contraseña: </label>
		<input required type="password" name="password" size="30">
		<button type="submit">Entrar</button>
	</form>
	<h4>¿No tienes cuenta? <a href="/registro">Registrate</a></h4>
	<a href="/cambiar-contraseña">¿Olvido su contraseña?</a>
</main>
