<div class="container">

	<h1>Iniciar sesión</h1>
	<div class="login-container">
		<div class="card login-card">
			<form manager="form" enctype="multipart/form-data" action="/">
				<label>Ingresa tu correo: </label>
				<input required type="email" name="email" size="30">
				<label>Ingresa tu contraseña: </label>
				<input required type="password" name="password" size="30">
				<button type="submit">Entrar</button>
			</form>
			<div>
				<h4>¿No tienes cuenta? <a href="/registro">Registrate</a></h4>
				<a href="/cambiar-contraseña">¿Olvido su contraseña?</a>
			</div>
		</div>
	</div>
</div>