<main class="container">
	<h1 class="t">¡Forme parte de nuestra comunidad!</h1>
	<p class="info">Cree una cuenta para ser parte de la comunidad más grande de viajes en ¡México!</p>
	<div class="login">
		<header class="login__header">
			<h2>Registro<i class="mu mu-cloud"></i></h2>
		</header>
		<form enctype="application/x-www-form-urlencoded" class="login__form" method="post">
			<div>
				<label>Correo electrónico:</label>
				<input required type="email" name="email" placeholder="mail@address.com">
			</div>
			<div>
				<label>Nombre completo:</label>
				<input required type="text" name="username" placeholder="Lee Joheon">
			</div>
			<div>
				<label>Contraseña:</label>
				<input required type="password" name="password_1" placeholder="password">
				<small>(Mínimo 8 caracteres)</small>			
			</div>
			<div>
				<label>Confirmar contraseña:</label>
				<input required type="password" name="password_2" placeholder="password">
			</div>
			<div>
				<button type="submit" class="btnlog">Registrarse</button>
			</div>
			<p><b>¿Ya está registrado?</b> <a href="/iniciar-sesion">Inicia sesión</a></p>
		</form>
	</div>
			<p class="info">Al crearse una cuenta usted acepta los <a href="/terminos">términos de privacidad</a> de nuestra página web</p>
</main>
