<main class="container">
	<h1>¡Forme parte de nuestra comunidad!</h1>
	<p>Cree una cuenta para ser parte de la comunidad mas grande de viajes en ¡Mexico!</p>
	<p>Al crearse una cuenta usted acepta los <a href="/terminos">terminos de privacidad</a> de nuestra pagina web</p>
	<h2>Registro</h2>
	<form enctype="application/x-www-form-urlencoded" method="post">
		<label>Correo electronico: </label>
		<div class="input-group">
		<input required type="mail" name="email" size="30">
		<i class="mu mu-mail floating"></i>
		</div>
		<label>Nombre de usuario: </label>
		<input required type="text" name="username" size="30">
		<label>Contraseña: </label>
		<input required type="password" name="password" size="30">
		<label>Confirmar contraseña: </label>
		<input required type="password" name="password2" size="30">
		<button type="submit">Registrarse</button>
	</form>
	<p><b>¿Ya estas registrado?</b> <a href="/iniciar-sesion">Inicia sesion</a></p>
</main>
