<div class="container">
    <div class="titulo">
        <h1>Listado de roles</h1>

        <div class="tabla">
            <table>
                <?php for($i = 0; $i < count($this->role); $i++) { ?>  <!-- Ciclo de la tabla -->
                <tr>                                            <!-- Fila -->
                    <td>                                        <!-- Columna -->
                        <?= $this->role[$i]['id'] ?>            <!-- Imprimir el id del rol-->
                    </td>  
                    <td> 
                        <?= $this->role[$i]['name'] ?>          <!-- Imprimir el nombre del rol-->
                    </td> 
                </tr>
                <?php } ?>
            </table>
        </div>
    </div>
</div>