<main class="container">
    <div class="img">
        <img class="animate__animated animate__backInLeft" src="/public/TimeTravel.png" alt="">
    </div>
    <h1 class="animate__animated animate__backInLeft">Términos y condiciones</h1>

    <div class="body">

        <p>Al utilizar Time Travel (sitio web acerca de viajes) aceptas expresamente y sin reservas cumplir con y quedar sujeto a los presentes Términos y Condiciones, los cuales podrán ser modificados por Time Travel en cualquier momento como se indica en estos mismos Términos y Condiciones.


            Por favor, revisa esta página regularmente por si hubiese cualquier cambio. Si no aceptas estos Términos y Condiciones no estás autorizado para, y no deberás, acceder ni utilizar este Sitio Web.

        <h2>¿QUÉ ES TIME TRAVEL?</h2>
        Es un sitio web que facilita la búsqueda de viajes en línea (como, por ejemplo, intercambio de experiencias y conocimientos acerca de buenos lugares para viajar) y otros servicios relacionados con viajes (los “servicios de Time Travel“) a usuarios de todo el mundo a través de nuestros sitios web y otras plataformas (por ejemplo, redes sociales).


        TIME TRAVEL no es una agencia de viajes o controla en ningún sentido la información, productos o servicios ofrecidos por terceros en o a través de este sitio o mediante los servicios u otras plataformas de TIME TRAVEL. La información publicada es ofrecida por meta-buscadores, aerolíneas, hoteles, operadores turísticos u otros terceros de forma independiente y están sujetos a los términos y condiciones impuestos por dichas terceras partes. No mantenemos ningún control sobre los proveedores.
        </p>
    </div>
</main>