<?php

use Modules\Utils;

?>
<main class="container">
    <h1>Listado de usuarios</h1>
    <table>
        <thead>
            <th>Id</th>
            <th>Nombre</th>
            <th>Rol</th>
            <th>Fecha de creacion</th>
            <th>Opciones</th>
        </thead>
        <?php foreach ($users as $user): ?>
        <tr>
            <td>
                <?= $user->id ?>
            </td>
            <td>
                <?= strip_tags($user->username) ?>
            </td>
            <td>
                <?= strip_tags($user->rol) ?>
            </td>
            <td>
                <?= Utils::date($user->creation) ?>
            </td>
            <td>
                <a role="button" href="/admin/usuario/editar?id=<?= $user->id ?>">
                    <i class="mu mu-edit"></i>
                    <span>Editar</span>
                </a>
                <a role="button" href="/admin/usuario/eliminar?id=<?= $user->id ?>">
                    <i class="mu mu-delete"></i>
                    <span>Eliminar</span>
                </a>
                <a role="button" href="/admin/usuario/banear?id=<?= $user->id ?>">
                    <i class="mu mu-cancel"></i>
                    <span>Banear</span>
                </a>
            </td>
        </tr>
        <?php endforeach ?>
    </table>
</main>
