'/':
  controller: 'TimeTravel\Controller\Main::index'

'/login':
  controller: 'TimeTravel\Controller\Login::log_in'

'/change':
  controller: 'TimeTravel\Controller\ChangeP::change'
  
'/register':
  controller: 'TimeTravel\Controller\Register::regis'
