<link rel="stylesheet" href="/public/assets/change.css">
<head > 
	<br><br><h1>Recuperar contraseña</h1><br><br><br>
</head>
<h3>Ingrese su correo electronico</h3><br><br>
<div>
	<form enctype="application/x-www-form-urlencoded" action="/login?submit" method="POST">
		<label for="input-correo">Ingresa tu correo  </label>
		<input type="text" id="input-correo" name="correo">
		<button>Recuperar</button>
	</form>
</div>