<!-- <link rel="stylesheet" href="/public/assets/change.css"> -->
<head > 
	<h1>Recuperar contraseña</h1>
</head>
<h3>Ingrese su correo electronico</h3>
<div>
	<form enctype="application/x-www-form-urlencoded" action="/change?submit" method="POST">
		<label for="input-correo">Ingresa tu correo</label>
		<input type="" name="correo" placeholder="example@example.xyz">
		<button>Enviar correo</button>
		<div class="mensaje">
			<?= $_self['mensaje'] ?? null ?>
		</div>
	</form>
	
</div>