
		<div id="header">
			<ul class="nav">
				<li><a href="">Inicio</a></li>
				<li><a href="">Roles</a>
					<ul id="primer_menu">
						<li><A HREF=""> Webmaster </A></li>    <!--Ejemplo: <A HREF="otra_pagina.html"> Este es un link </A> !-->
						<li><A HREF=""> Moderador </A></li>
						<li><A HREF=""> Diseñador </A></li>
						<li><A HREF=""> Editor de texto </A></li>

							
						</li>
					</ul>
				</li>
				<li><a href="">Usuarios</a>
					<ul>
						<li><A HREF="Poner archivophtml para la pagina"> Configuración </A></li>
						<li><a href="/admin/eliminar_rol">Gestionar Permisos</a></li>


					</ul>
				</li>
        <li><a href="">Otros</a>
					<ul>
						<li><A HREF="Link_reacciones">Reacciones</A></li>
					</ul>
				</li>
				<li><A HREF="/admin/contacto">Contacto</a></li>
			</ul>
		</div>
 
<div class="margin-auto">
  <span class="margin-auto__content">
   ¡¡Bienvenidoo a la página del admin!!
  </span>
</div>

