<div class="container">
<h1> ¡Contactanos! </h1>
<!--<img src="../beach.png"></img> !--> <!--No me dió tiempo para poner bien la imagen !-->
<form enctype="application/x-www-form-urlencoded"  action="/" manager="form">

		<label for="input-correo">Ingresa tu correo</label>
        <input required class="inpt" type="text" id="input-correo" name="email" ><br>
        <label for="input-mensaje">Escribe el mensaje deseado</label>
		<input required class="inpt" type="text" id="input-mensaje" name="message" ><br>

	<button type="submit" class="btn primary">Enviar</button>
	</form>
</div>