<div class="container">
    <div class="titulo">
        <h1>Crear roles de usuario</h1>

        <h2>Crear un nuevo rol</h2><br>
    </div>
    <form action="/admin" manager="form" class="selector" method="POST" enctype="application/x-www-form-urlencode">
        <input type="text" placeholder="Nombre del rol" name="nombre">
        <button>
            Enviar
        </button>
    </form>
</div>