<div class="container">
<h1> Cambiar informacion de los usuarios </h1>
<form manager="form" method="POST"  enctype="multipart/form-data">

		<label for="cambiar-correo">Editar correo</label>
		<div class="edit">
		<input type="text" id="input-correo" name="email">
		</div>

		<label for="name">Editar nombre</label>
		<div class="edit">
			<input  type="text" id="input-nombre" name="name">
		</div>

		<label for="name">Editar rol</label>
		<div class="edit">
			<input  type="text" id="input-nombre" name="rol">
		</div>

		<label for="Cambiar-Foto">Cambiar foto</label>
		<div class="edit">
		<input type="file" id="input-imagen" name="avatar">
		</div>
	<button type="submit" class="btn primary">Actualizar información</button>
	</form>
</div>