<div class="container">
<h1> Cambio de informacion de usuario </h1>
<form enctype="application/x-www-form-urlencoded"  manager="form">

		<label for="cambiar-correo">Editar correo</label>
		<div class="edit">
		<input type="text" id="input-correo" name="email">
					<button type="submit">
					<object data="/public/icons/edit.svg" class="icon"></object>
					</button>
		</div>

		<label for="name">Editar nombre</label>
		<div class="edit">
		<input  type="text" id="input-nombre" name="name">
					<button type="submit">
					<object data="/public/icons/edit.svg" class="icon"></object>
					</button>
		</div>

		<label for="Cambiar-Foto">Cambiar foto</label>
		<div class="edit">
		<input type="file" id="input-imagen" name="avatar">
					<button type="submit">
					<object data="/public/icons/edit.svg" class="icon"></object>
					</button>
		</div>
	<button type="submit" class="btn primary">Actualizar información</button>
	</form>
</div>