<div class="container">
	<h1> Cambiar informacion de los usuarios </h1>
	<form manager="form" method="POST" enctype="multipart/form-data">

		<label for="name">Editar nombre</label>
		<div class="edit">
			<input type="text" id="input-nombre" name="name" value=" <?= $this->user->username ?>">
		</div>

		<div class="avatar">
			<br>
			<label for="avatar">Imagen anterior</label>
			<?php if (!is_null($this->image)): ?>
				<img src="<?= $this->image->url() ?>" >
			<?php endif ?>
		</div>
		<br><br>
		<label for="Cambiar-Foto">Cambiar foto</label>
		<input type="file" name="avatar">
		<a href="/perfil"><input type="button" value="Regresar a mi perfil"></a><br>
		<button type="submit">Actualizar informacion</button>
	</form>
</div>