<select id="default_role" name="default_role">
    <option selected="">Gestión de permisos</option>
    <option value="Webmaster">Webmaster</option>
    <option value="moderador">Moderador</option>
    <option value="analista">Analista</option>
    <option value="gestor_de_contenidos">Gestor de contenidos</option>
     <option value="admin">Administrador general</option>
</select>

 
<div class="margin-auto">
  <span class="margin-auto__content">
   Sección de eliminación de roles
  </span>
</div>