<div class="container">
    <h1> Eliminar cuenta </h1>
    <form manager="form" method="POST" enctype="multipart/form-data" action="/admin/ver-usuarios">

        <label for="name">Una vez elimines este usuario, no podra volver a iniciar sesion</label>
        <div>
            <a href="/admin/ver-usuarios"><input type="button" value="Regresar a lista de usuarios"></a><br>
            <button type="submit">Eliminar usuario</button>
        </div>
    </form>
</div>