<div class="container">
	<h1>Titulo 1</h1>
	<button class="btn">Btn1</button>
	<a>Ref1</a>
	<a href="ref">Ref1</a>
	<a class="btn" href="ref">Ref1</a>

	<form>
		<input type="text">
		<input type="file">
		<input type="date">
		<input type="number">
		<input type="submit" value="Btn2">
		<input type="button" value="Btn2">
		<textarea></textarea>
	</form>

	<nav>
		<a>Ref1</a>
		<a href="ref">Ref1</a>
		<a class="btn" href="ref">Ref1</a>
	</nav>

	<img src="/public/beach.png">
</div>
