<main>
	<h1>Ultimas publicaciones: </h1>
	<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cum, explicabo beatae? Doloribus beatae porro repellendus aut, consequuntur est id maxime obcaecati placeat. In asperiores dolorum amet commodi dolorem quibusdam nostrum veritatis? Asperiores architecto error, itaque quaerat porro voluptas consectetur numquam iste aut libero? Possimus dignissimos culpa distinctio dolorem soluta natus nobis dicta laboriosam magni odit sunt consectetur id exercitationem fuga sapiente, deleniti delectus magnam aut hic explicabo deserunt illo quo illum. Qui explicabo ad cum cumque vero ratione nam aut blanditiis saepe alias exercitationem provident maiores ut repudiandae velit laudantium, molestiae soluta culpa beatae. Quis magnam ea quia incidunt voluptatibus repellendus, cumque, sit a temporibus libero reprehenderit eveniet tempore odio natus. Culpa voluptatum suscipit molestiae repudiandae quis odit. Ipsa dolorum repellat accusantium alias?</p>
    <input type="date">
    <input type="datetime-local">
    <input type="email">
    <input type="month">
    <input type="number">
    <input type="password">
    <input type="search">
    <input type="tel">
    <input type="text">
    <input type="time">
    <input type="url">
    <input type="week">
    <textarea></textarea>
	<button>Hola</button>
    <input type="button">
    <input type="checkbox">
    <input type="color">
    <input type="file">
    <input type="hidden">
    <input type="image">
    <input type="radio">
    <input type="range">
    <input type="reset">
    <input type="submit">
	<a href="." role="button">Hola</a>
</main>
