<div class="container">
    
<h1>Listado de usuarios</h1>
<table>
<tr>
        <th>Id</th>
        <th>Nombre</th>
        <th>Rol</th>
    </tr>
<?php for($i = 0; $i < count($this->usuarios); $i++) { ?>  
<tr>                                            
    <td>                                        
        <?= $this->usuarios[$i]['id'] ?>         
    </td>  
    <td> 
        <?= $this->usuarios[$i]['username'] ?>        
    </td> 
    <td> 
        <?= $this->usuarios[$i]['rol'] ?>        
    </td> 
</tr>
<?php } ?>
</table>  
</div>

