<div class="container">
	<h1>Iniciar sesión</h1>
	<div class="login-container">
		<div class="card login-card">
			<form manager="form" enctype="multipart/form-data" action="/">
				<label>Ingresa tu correo: </label>
				<input required type="email" name="email" size="30">
				<label>Ingresa tu contraseña: </label>
				<input required type="password" name="password" size="30">
				<button type="submit">Entrar</button>
			</form>
			<div>
				<h4>¿No tienes cuenta? <a href="/registro">Registrate</a></h4>
				<a href="/cambiar-contraseña">¿Olvido su contraseña?</a>
			</div>
		</div>
		<div class="login-info">	
			Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus, eveniet tenetur, consequuntur beatae quo minima aperiam nostrum quos deserunt ratione praesentium sed nesciunt, minus cum quisquam soluta optio velit et tempora officia. Nihil praesentium consequatur blanditiis. Fugit itaque assumenda eaque officiis id possimus, corrupti quibusdam accusantium labore est cum totam atque asperiores veritatis dicta autem magni. Vitae dolore, aspernatur ex quod ducimus perferendis praesentium doloremque rerum maxime animi mollitia est cupiditate in quidem et, cumque porro voluptates laboriosam similique natus voluptas! Nemo, sed rem? Cupiditate accusamus illo voluptates laudantium! Soluta non dolorum totam. Ea, nisi. Perspiciatis veritatis dicta nemo, ad voluptas ipsa ea deserunt nobis error sint quia quasi libero velit debitis eligendi optio eaque autem omnis cumque obcaecati consequatur unde. Odit, cupiditate!
		</div>
	</div>
</div>
