<?php use Controller\Component\Navbar; ?>
<?php use Modules\Kernel\View; ?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title><?= $view->title; ?></title>

	<!-- Site stylesheets -->
	<link href="/public/global.css" rel="stylesheet">
	<link href="/public/theme.css" rel="stylesheet">
	<link href="/public/site.css" rel="stylesheet">

	<?php foreach($view->styles as $style_href): ?>
	<link href="/public/<?= $style_href; ?>" rel="stylesheet">
	<?php endforeach; ?>

	<!-- Site scripts -->
	<script src="/public/main.js" type="module"></script>
	<?php foreach($view->scripts as $script_src): ?>
	<script src="/public/<?= $style_ref; ?>" type="module"></script>
	<?php endforeach; ?>
</head>
<body>
	<?php View::render(new Navbar); ?>
	<div class="message-container">
		<div class="messages">
		<?php foreach($view->messages as $message): ?>
			<?php View::render($message); ?>
		<?php endforeach; ?>
		</div>
	</div>
	<main id="main-container">
		<?php View::render($view->content); ?>
	</main>
</body>
</html>
