<div class="container">
    <img src="https://www.bbva.com/wp-content/uploads/2021/03/noruega.jpg">
    <div>
        <div class="header">
            <span>autor: Jooheon</span>    
            <span class="text-right">fecha: 06 de Octubre</span>
        </div>
        <h2>
            N O R U E G A
        </h2>
        <div class="body">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui quaerat totam quia. In consequuntur perferendis, tenetur obcaecati corrupti porro voluptatibus, aspernatur praesentium aliquam labore laboriosam quisquam, sed at et dignissimos?
        </div>
    </div>
    <button>
        <object data="/public/icons/heart.svg"></object>
        400
    </button>
</div>