<div class="container">
	<?php if(isset($view->pub)): ?>
	<h1><?= $view->pub->title; ?></h1>
	<?php else: ?>
	<h1>Nueva publicacion</h1>
	<?php endif; ?>
	<form enctype="multipart/form-data" action="?e=submit" method="POST">
		<div class="field">
			<label for="pub-title">Titulo</label>
			<input required class="inpt" type="text" id="pub-title" name="title">
		</div>
		<div class="field">
			<label for="pub-body">Contenido</label>
			<textarea required class="inpt" id="pub-body" name="body"></textarea>
		</div>
		<div class="field">
			<label for="pub-image">Imagen</label>
			<input required class="inpt" type="file" id="pub-image" name="image">
		</div>
		<button type="submit" class="btn primary">Entrar</button>
	</form>
</div>
