<div class="container">
	<h1>Registro</h1>

	<form enctype="application/x-www-form-urlencoded" action="?e=submit" method="POST">
		<label>Correo electronico: </label>
		<input required type="mail" name="email">
		<label>Nombre de usuario: </label>
		<input required type="text" name="username">
		<label>Contraseña: </label>
		<input required type="password" name="password[]">
		<label>Confirmar contraseña: </label>
		<input required type="password" name="password[]">
		<button type="submit">Registrarse</button>
	</form>
	<p><b>¿Ya estas registrado?</b> <a href="/iniciar-sesion">Inicia sesion</a></p>
<div>
