<div class="container">
	<h1>Registro</h1>

	<form enctype="application/x-www-form-urlencoded"  action="/" manager="form">
		<label>Ingrese una imagen de usuario</label>
		<input type="file" name="avatar">
		<label>Correo electronico: </label>
		<input required type="mail" name="email">
		<label>Nombre de usuario: </label>
		<input required type="text" name="username">
		<label>Contraseña: </label>
		<input required type="password" name="password">
		<label>Confirmar contraseña: </label>
		<input required type="password" name="password2">
		<button type="submit">Registrarse</button>
	</form>
	<p><b>¿Ya estas registrado?</b> <a href="/iniciar-sesion">Inicia sesion</a></p>
<div>
