<nav id="site-nav">
	<div class="branding">
		<h1><?= $_ENV['Site']['name']; ?></h1>
	</div>
	<div class="options">
		<form action="search" method="GET">
			<input name="q" type="text" required>
			<button type="submit" class="btn secondary">Ir</button>
		</form>
		<?php if(isset($view->user)): ?>
		<?php else: ?>
			<a href="/login">Iniciar sesion</a>
			<a href="/register">Registrarse</a>
		<?php endif; ?>
	</div>
</nav>
