<?php use Modules\Kernel\Session; ?>

<nav class="navbar primary" id="main-nav">
	<div class="head">
		<a class="logo" href="/"><?= $_ENV['Site']['name']; ?></a>
		<button class="btn burger" event-type="nav-toggle" data-target="main-nav">
			<object class="icon" data="/public/icons/menu.svg"></object>
		</button>	
	</div>
	<div class="items">
		<form action="search" method="GET">
			<div class="inpt-search">
				<input required name="q" class="inpt" type="text" placeholder="Buscar...">
				<button class="btn" type="submit">
					<object class="icon" data="/public/icons/search.svg"></object>
				</button>
			</div>
		</form>
		<?php if(Session::isLogged()): ?>
		<a class="btn" href="/login">Iniciar sesion</a>
		<?php else: ?>
		<a class="btn" href="/login">Iniciar sesion</a>
		<a class="btn" href="/registro">Registrarse</a>
		<?php endif; ?>
	</div>
</nav>
