<h1>Log-in</h1>
<div>
	<form enctype="application/x-www-form-urlencoded" action="/login?submit" method="POST">
		<label for="input-correo">Ingresa tu correo</label>
		<input type="text" id="input-correo" name="correo">
		<label for="input-contraseña">Ingresa tu contraseña</label>
		<input type="password" id="input-contraseña" name="contraseña">
		<button>Entrar</button>
	</form>
</div>
<div>
	<h4>¿No tienes cuenta? <a href="Registro.html">Registrate</a></h4>
	<a href="ContraseñaOlvidada.html">¿Olvido su contraseña?</a>
</div>
