<nav class="navbar" id="admin-nav">
	<div class="items">
		<a role="button" href="/admin">
			<i class="mu mu-chapters"></i>
			<span class="tooltip">Administracion</span>
		</a>
		<a role="button" href="/admin/publicaciones">
			<i class="mu mu-edit"></i>
			<span class="tooltip">Publicaciones</span>
		</a>
		<a role="button" href="/admin/roles">
			<i class="mu mu-lock"></i>
			<span class="tooltip">Roles</span>
		</a>
		<a role="button" href="/admin/usuarios">
			<i class="mu mu-group"></i>
			<span class="tooltip">Usuarios</span>
		</a>
		<a role="button" href="/admin/archivos">
			<i class="mu mu-file"></i>
			<span class="tooltip">Archivos</span>
		</a>
	</div>
</nav>
