<nav id="main-navigation" class="navbar">
</nav>

<!--	<div class="navbar-container">
<!--		<a href="/" class="navbar-title navbar-left">
<!--			<h1><?= SITE_NAME ?></h1>
<!--		</a>
<!--		<form class="center" action="/post/buscar" method="get">
<!--			<div class="input-container">
<!--				<input type="search" placeholder="Buscar...">
<!--				<i class="floating mu mu-search"></i>
<!--			</div>
<!--		</form>
<!--	</div>
<!--	<div class="items">
<!--		<a href="/iniciar-sesion" role="button">Inicar sesion</a>
<!--		<a href="/registro" role="button">Registro</a>
<!--		<button class="menu-toggle">
<!--			<i class="mu mu-menu"></i>
<!--		</button>
<!--	</div>
