<nav id="main-navigation" class="navbar">
    <button class="back-button" element="go-back">
        <i class="mu mu-arrow-left"></i>
    </button>
    <a href="/" class="brand">
        <h1 class="title">
            <?= htmlentities(SITE_NAME) ?>
        </h1>
    </a>
    <form action="/buscar" class="search">
        <div class="input-group">
            <input type="search" name="q">
            <i class="mu mu-search floating"></i>
        </div>
    </form>
    <div class="items" element="items">
        <?php if ($_SESSION['logged']) : ?>
        <a href="/perfil" role="button" class="profile item">
            <div class="pfp">
            <?php if(!empty($_SESSION['pfp'])): ?>
                <img src="<?= $_SESSION['pfp']->url() ?>" class="contains" loading="lazy" alt="Imagen de perfil">
            <?php else: ?>
                <img src="/public/user.png" class="contains" loading="lazy" alt="Imagen de perfil">
            <?php endif ?>
            </div>
            <span>
                <?= htmlentities($_SESSION['account']['username']) ?>
            </span>
        </a>
        <a href="/salir" role="button">Cerrar sesion</a>
        <?php else : ?>
        <a href="/iniciar-sesion" role="button">Inicar sesion</a>
        <a href="/registro" role="button">Registro</a>
        <?php endif ?>
    </div>
    <div class="mobile-items">
        <button element="items-toggle">
            <i class="mu mu-menu"></i>
        </button>
    </div>
</nav>
