<?php

use Modules\Kernel\Message;

?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title><?= $title ?></title>
	<link href="/public/favicon.ico" rel="icon" />
	<link href="/public/global.css" rel="stylesheet" />
	<link href="/public/site.css" rel="stylesheet" />
	<link href="/public/site-small.css" rel="stylesheet" media="(max-width: 800px)" />
	<script src="/public/main.js" type="module"></script>
</head>
<body>
	<div id="site-alerts" class="alerts">
		<?php while($message = Message::get()): ?>
			<?= $message ?>
		<?php endwhile ?>
	</div>
	<?= $content ?>
</body>
</html>
